const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  selectVideo: () => ipcRenderer.invoke('select-video'),
  selectOutput: () => ipcRenderer.invoke('select-output'),
  getVideoInfo: (path) => ipcRenderer.invoke('get-video-info', path),
  transcribeAudio: (path) => ipcRenderer.invoke('transcribe-audio', path),
  extractClip: (opts) => ipcRenderer.invoke('extract-clip', opts),
  batchExtractClips: (opts) => ipcRenderer.invoke('batch-extract-clips', opts),
  exportVideo: (opts) => ipcRenderer.invoke('export-video', opts),
  clearSegments: () => ipcRenderer.invoke('clear-segments'),
  buildPreview: (opts) => ipcRenderer.invoke('build-preview', opts),
  projectList: () => ipcRenderer.invoke('project-list'),
  projectGet: (id) => ipcRenderer.invoke('project-get', id),
  projectSave: (id, data) => ipcRenderer.invoke('project-save', id, data),
  projectDelete: (id) => ipcRenderer.invoke('project-delete', id),
  projectRename: (id, name) => ipcRenderer.invoke('project-rename', id, name),
  copyVideo: (opts) => ipcRenderer.invoke('copy-video', opts),
  deleteVideoFile: (filePath) => ipcRenderer.invoke('delete-video-file', filePath),
  settingsGetAll: () => ipcRenderer.invoke('settings-get-all'),
  settingsGet: (key) => ipcRenderer.invoke('settings-get', key),
  settingsSet: (key, value) => ipcRenderer.invoke('settings-set', key, value),
  minimize: () => ipcRenderer.send('win-minimize'),
  maximize: () => ipcRenderer.send('win-maximize'),
  close: () => ipcRenderer.send('win-close'),
  onTranscribeProgress: (cb) => { ipcRenderer.on('transcribe-progress', (e, d) => cb(d)); },
  offTranscribeProgress: (cb) => { ipcRenderer.removeListener('transcribe-progress', cb); },
  onBatchExtractProgress: (cb) => { ipcRenderer.on('batch-extract-progress', (e, d) => cb(d)); },
  offBatchExtractProgress: (cb) => { ipcRenderer.removeListener('batch-extract-progress', cb); },
  onPreviewReady: (cb) => { ipcRenderer.on('preview-ready', (e, p) => cb(p)); },
  onMaximizeChange: (cb) => { ipcRenderer.on('win-maximize-change', (e, m) => cb(m)); },
  pluginList: () => ipcRenderer.invoke('plugin-list'),
  pluginLoadRenderer: (name) => ipcRenderer.invoke('plugin-load-renderer', name),
  pluginImportZip: () => ipcRenderer.invoke('plugin-import-zip'),
  pluginImportFolder: () => ipcRenderer.invoke('plugin-import-folder'),
  pluginDelete: (name) => ipcRenderer.invoke('plugin-delete', name),
  pluginInvoke: (pluginName, channel, ...args) => ipcRenderer.invoke('plugin:' + pluginName + ':' + channel, ...args),
  onPluginEvent: (pluginName, channel, cb) => { ipcRenderer.on('plugin:' + pluginName + ':' + channel, (e, d) => cb(d)); },
  pluginIcon: (name) => ipcRenderer.invoke('plugin-icon', name),
  uiPackList: () => ipcRenderer.invoke('ui-pack-list'),
  uiPackApply: (name) => ipcRenderer.invoke('ui-pack-apply', name),
  uiPackImportZip: () => ipcRenderer.invoke('ui-pack-import-zip'),
  uiPackDelete: (name) => ipcRenderer.invoke('ui-pack-delete', name),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  checkForUpdate: () => ipcRenderer.invoke('check-for-update'),
  onUpdateAvailable: (cb) => { ipcRenderer.on('update-available', (e, d) => cb(d)); },
  fileExists: (p) => ipcRenderer.invoke('file-exists', p),
  logOpenDir: () => ipcRenderer.invoke('log-open-dir'),
  logWrite: (level, ...args) => ipcRenderer.invoke('log-write', { level, args }),
});
